### ISSUE TITLE
SHIT'S BROKE

### ISSUE THREAD

**Issue by IAMAVelociraptorAMA** [mutoid/ccbot#22] opened 2017-03-13 16:31 UTC
LET US QUOTE WITH @FUNCTIONALITY

**Comment by citz** [comment] 2017-03-13 16:36
I made this ticket too but better

**Comment by mutoid** [comment] 2017-03-13 17:30
Duplicate of earlier issue #25

**Closed as completed by mutoid** 2017-03-13 17:30 UTC
Labels: duplicate

**Comment by citz** [comment] 2017-03-17 04:14
my ticket was better

**Comment by citz** [comment] 2017-03-17 04:17
lol muty you closed both tickets

I'm on to you, you're just trying to get out of work!
